INSERT  INTO
	lh_s_role
      ( 
      ID       
      ,ROLE_CODE
      ,ROLE_NAME                      
      ,CREATE_BY                      
      ,XCX_ID                         
      ,USER_TYPE                      
      ) 
values
      (
      :lhSRole.id  
      ,:lhSRole.roleCode  
      ,:lhSRole.roleName                      
      ,:lhSRole.createBy                      
      ,:lhSRole.xcxId                         
      ,:lhSRole.userType                      
      )